// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="multi_axim,hls_ip_2015_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=28,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=4,HLS_SYN_FF=845,HLS_SYN_LUT=988}" *)

module multi_axim (
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        interrupt
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 12'b1;
parameter    ap_ST_st2_fsm_1 = 12'b10;
parameter    ap_ST_st3_fsm_2 = 12'b100;
parameter    ap_ST_st4_fsm_3 = 12'b1000;
parameter    ap_ST_st5_fsm_4 = 12'b10000;
parameter    ap_ST_st6_fsm_5 = 12'b100000;
parameter    ap_ST_st7_fsm_6 = 12'b1000000;
parameter    ap_ST_pp0_stg0_fsm_7 = 12'b10000000;
parameter    ap_ST_st17_fsm_8 = 12'b100000000;
parameter    ap_ST_st18_fsm_9 = 12'b1000000000;
parameter    ap_ST_st19_fsm_10 = 12'b10000000000;
parameter    ap_ST_st20_fsm_11 = 12'b100000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    ap_const_int64_8 = 8;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv4_F = 4'b1111;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv4_A = 4'b1010;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_true = 1'b1;
parameter    C_S_AXI_AXILITES_WSTRB_WIDTH = (C_S_AXI_AXILITES_DATA_WIDTH / ap_const_int64_8);
parameter    C_S_AXI_WSTRB_WIDTH = (C_S_AXI_DATA_WIDTH / ap_const_int64_8);
parameter    C_M_AXI_GMEM_WSTRB_WIDTH = (C_M_AXI_GMEM_DATA_WIDTH / ap_const_int64_8);
parameter    C_M_AXI_WSTRB_WIDTH = (C_M_AXI_DATA_WIDTH / ap_const_int64_8);

input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1 : 0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1 : 0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1 : 0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1 : 0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1 : 0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1 : 0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1 : 0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1 : 0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1 : 0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1 : 0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1 : 0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1 : 0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1 : 0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1 : 0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1 : 0] m_axi_gmem_BUSER;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm = 12'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_53;
reg    ap_ready;
wire   [31:0] x;
wire   [31:0] y;
wire   [31:0] ap_return;
wire    multi_axim_AXILiteS_s_axi_U_ap_dummy_ce;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
wire   [31:0] gmem_AWADDR;
wire   [0:0] gmem_AWID;
wire   [31:0] gmem_AWLEN;
wire   [2:0] gmem_AWSIZE;
wire   [1:0] gmem_AWBURST;
wire   [1:0] gmem_AWLOCK;
wire   [3:0] gmem_AWCACHE;
wire   [2:0] gmem_AWPROT;
wire   [3:0] gmem_AWQOS;
wire   [3:0] gmem_AWREGION;
wire   [0:0] gmem_AWUSER;
reg    gmem_WVALID;
wire    gmem_WREADY;
wire   [31:0] gmem_WDATA;
wire   [3:0] gmem_WSTRB;
wire    gmem_WLAST;
wire   [0:0] gmem_WID;
wire   [0:0] gmem_WUSER;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
wire   [31:0] gmem_ARADDR;
wire   [0:0] gmem_ARID;
wire   [31:0] gmem_ARLEN;
wire   [2:0] gmem_ARSIZE;
wire   [1:0] gmem_ARBURST;
wire   [1:0] gmem_ARLOCK;
wire   [3:0] gmem_ARCACHE;
wire   [2:0] gmem_ARPROT;
wire   [3:0] gmem_ARQOS;
wire   [3:0] gmem_ARREGION;
wire   [0:0] gmem_ARUSER;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
reg    gmem_BREADY;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
wire    multi_axim_gmem_m_axi_U_ap_dummy_ce;
reg   [3:0] i_reg_103;
reg   [29:0] tmp_reg_176;
reg   [29:0] tmp_4_reg_181;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_220;
reg    ap_sig_ioackin_gmem_ARREADY;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_233;
reg    ap_sig_ioackin_gmem_AWREADY;
wire   [0:0] exitcond_fu_154_p2;
reg   [0:0] exitcond_reg_197;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_7;
reg    ap_sig_bdd_246;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_sig_bdd_254;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_197_pp0_it7;
reg    ap_sig_ioackin_gmem_WREADY;
reg    ap_reg_ppiten_pp0_it8 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_197_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_197_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_197_pp0_it3;
reg   [0:0] ap_reg_ppstg_exitcond_reg_197_pp0_it4;
reg   [0:0] ap_reg_ppstg_exitcond_reg_197_pp0_it5;
reg   [0:0] ap_reg_ppstg_exitcond_reg_197_pp0_it6;
wire   [3:0] i_1_fu_160_p2;
reg  signed [31:0] gmem_addr_1_read_reg_206;
wire  signed [31:0] grp_fu_171_p2;
reg  signed [31:0] tmp_2_reg_217;
wire   [63:0] tmp_6_fu_134_p1;
wire   [63:0] tmp_5_fu_144_p1;
reg    ap_reg_ioackin_gmem_ARREADY = 1'b0;
reg    ap_reg_ioackin_gmem_AWREADY = 1'b0;
reg    ap_reg_ioackin_gmem_WREADY = 1'b0;
reg    ap_sig_cseq_ST_st20_fsm_11;
reg    ap_sig_bdd_356;
wire  signed [31:0] grp_fu_171_p0;
wire  signed [31:0] grp_fu_171_p1;
reg    grp_fu_171_ce;
reg   [11:0] ap_NS_fsm;
reg    ap_sig_bdd_447;
reg    ap_sig_bdd_446;


multi_axim_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
multi_axim_AXILiteS_s_axi_U(
    .AWVALID( s_axi_AXILiteS_AWVALID ),
    .AWREADY( s_axi_AXILiteS_AWREADY ),
    .AWADDR( s_axi_AXILiteS_AWADDR ),
    .WVALID( s_axi_AXILiteS_WVALID ),
    .WREADY( s_axi_AXILiteS_WREADY ),
    .WDATA( s_axi_AXILiteS_WDATA ),
    .WSTRB( s_axi_AXILiteS_WSTRB ),
    .ARVALID( s_axi_AXILiteS_ARVALID ),
    .ARREADY( s_axi_AXILiteS_ARREADY ),
    .ARADDR( s_axi_AXILiteS_ARADDR ),
    .RVALID( s_axi_AXILiteS_RVALID ),
    .RREADY( s_axi_AXILiteS_RREADY ),
    .RDATA( s_axi_AXILiteS_RDATA ),
    .RRESP( s_axi_AXILiteS_RRESP ),
    .BVALID( s_axi_AXILiteS_BVALID ),
    .BREADY( s_axi_AXILiteS_BREADY ),
    .BRESP( s_axi_AXILiteS_BRESP ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( multi_axim_AXILiteS_s_axi_U_ap_dummy_ce ),
    .ap_start( ap_start ),
    .interrupt( interrupt ),
    .ap_ready( ap_ready ),
    .ap_done( ap_done ),
    .ap_idle( ap_idle ),
    .ap_return( ap_return ),
    .x( x ),
    .y( y )
);

multi_axim_gmem_m_axi #(
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
multi_axim_gmem_m_axi_U(
    .AWVALID( m_axi_gmem_AWVALID ),
    .AWREADY( m_axi_gmem_AWREADY ),
    .AWADDR( m_axi_gmem_AWADDR ),
    .AWID( m_axi_gmem_AWID ),
    .AWLEN( m_axi_gmem_AWLEN ),
    .AWSIZE( m_axi_gmem_AWSIZE ),
    .AWBURST( m_axi_gmem_AWBURST ),
    .AWLOCK( m_axi_gmem_AWLOCK ),
    .AWCACHE( m_axi_gmem_AWCACHE ),
    .AWPROT( m_axi_gmem_AWPROT ),
    .AWQOS( m_axi_gmem_AWQOS ),
    .AWREGION( m_axi_gmem_AWREGION ),
    .AWUSER( m_axi_gmem_AWUSER ),
    .WVALID( m_axi_gmem_WVALID ),
    .WREADY( m_axi_gmem_WREADY ),
    .WDATA( m_axi_gmem_WDATA ),
    .WSTRB( m_axi_gmem_WSTRB ),
    .WLAST( m_axi_gmem_WLAST ),
    .WID( m_axi_gmem_WID ),
    .WUSER( m_axi_gmem_WUSER ),
    .ARVALID( m_axi_gmem_ARVALID ),
    .ARREADY( m_axi_gmem_ARREADY ),
    .ARADDR( m_axi_gmem_ARADDR ),
    .ARID( m_axi_gmem_ARID ),
    .ARLEN( m_axi_gmem_ARLEN ),
    .ARSIZE( m_axi_gmem_ARSIZE ),
    .ARBURST( m_axi_gmem_ARBURST ),
    .ARLOCK( m_axi_gmem_ARLOCK ),
    .ARCACHE( m_axi_gmem_ARCACHE ),
    .ARPROT( m_axi_gmem_ARPROT ),
    .ARQOS( m_axi_gmem_ARQOS ),
    .ARREGION( m_axi_gmem_ARREGION ),
    .ARUSER( m_axi_gmem_ARUSER ),
    .RVALID( m_axi_gmem_RVALID ),
    .RREADY( m_axi_gmem_RREADY ),
    .RDATA( m_axi_gmem_RDATA ),
    .RLAST( m_axi_gmem_RLAST ),
    .RID( m_axi_gmem_RID ),
    .RUSER( m_axi_gmem_RUSER ),
    .RRESP( m_axi_gmem_RRESP ),
    .BVALID( m_axi_gmem_BVALID ),
    .BREADY( m_axi_gmem_BREADY ),
    .BRESP( m_axi_gmem_BRESP ),
    .BID( m_axi_gmem_BID ),
    .BUSER( m_axi_gmem_BUSER ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( multi_axim_gmem_m_axi_U_ap_dummy_ce ),
    .I_ARVALID( gmem_ARVALID ),
    .I_ARREADY( gmem_ARREADY ),
    .I_ARADDR( gmem_ARADDR ),
    .I_ARID( gmem_ARID ),
    .I_ARLEN( gmem_ARLEN ),
    .I_ARSIZE( gmem_ARSIZE ),
    .I_ARLOCK( gmem_ARLOCK ),
    .I_ARCACHE( gmem_ARCACHE ),
    .I_ARQOS( gmem_ARQOS ),
    .I_ARPROT( gmem_ARPROT ),
    .I_ARUSER( gmem_ARUSER ),
    .I_ARBURST( gmem_ARBURST ),
    .I_ARREGION( gmem_ARREGION ),
    .I_RVALID( gmem_RVALID ),
    .I_RREADY( gmem_RREADY ),
    .I_RDATA( gmem_RDATA ),
    .I_RID( gmem_RID ),
    .I_RUSER( gmem_RUSER ),
    .I_RRESP( gmem_RRESP ),
    .I_RLAST( gmem_RLAST ),
    .I_AWVALID( gmem_AWVALID ),
    .I_AWREADY( gmem_AWREADY ),
    .I_AWADDR( gmem_AWADDR ),
    .I_AWID( gmem_AWID ),
    .I_AWLEN( gmem_AWLEN ),
    .I_AWSIZE( gmem_AWSIZE ),
    .I_AWLOCK( gmem_AWLOCK ),
    .I_AWCACHE( gmem_AWCACHE ),
    .I_AWQOS( gmem_AWQOS ),
    .I_AWPROT( gmem_AWPROT ),
    .I_AWUSER( gmem_AWUSER ),
    .I_AWBURST( gmem_AWBURST ),
    .I_AWREGION( gmem_AWREGION ),
    .I_WVALID( gmem_WVALID ),
    .I_WREADY( gmem_WREADY ),
    .I_WDATA( gmem_WDATA ),
    .I_WID( gmem_WID ),
    .I_WUSER( gmem_WUSER ),
    .I_WLAST( gmem_WLAST ),
    .I_WSTRB( gmem_WSTRB ),
    .I_BVALID( gmem_BVALID ),
    .I_BREADY( gmem_BREADY ),
    .I_BRESP( gmem_BRESP ),
    .I_BID( gmem_BID ),
    .I_BUSER( gmem_BUSER )
);

multi_axim_mul_32s_32s_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
multi_axim_mul_32s_32s_32_6_U0(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( grp_fu_171_p0 ),
    .din1( grp_fu_171_p1 ),
    .ce( grp_fu_171_ce ),
    .dout( grp_fu_171_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ioackin_gmem_ARREADY assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_gmem_ARREADY
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_ARREADY <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
            if (~(ap_const_logic_0 == ap_sig_ioackin_gmem_ARREADY)) begin
                ap_reg_ioackin_gmem_ARREADY <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == gmem_ARREADY)) begin
                ap_reg_ioackin_gmem_ARREADY <= ap_const_logic_1;
            end
        end
    end
end

/// ap_reg_ioackin_gmem_AWREADY assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_gmem_AWREADY
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_AWREADY <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
            if (~(ap_const_logic_0 == ap_sig_ioackin_gmem_AWREADY)) begin
                ap_reg_ioackin_gmem_AWREADY <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == gmem_AWREADY)) begin
                ap_reg_ioackin_gmem_AWREADY <= ap_const_logic_1;
            end
        end
    end
end

/// ap_reg_ioackin_gmem_WREADY assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_gmem_WREADY
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_WREADY <= ap_const_logic_0;
    end else begin
        if (ap_sig_bdd_446) begin
            if (~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
                ap_reg_ioackin_gmem_WREADY <= ap_const_logic_0;
            end else if (ap_sig_bdd_447) begin
                ap_reg_ioackin_gmem_WREADY <= ap_const_logic_1;
            end
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_7) & ~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(exitcond_fu_154_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(ap_const_logic_0 == ap_sig_ioackin_gmem_AWREADY))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_7) & ~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (exitcond_fu_154_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(ap_const_logic_0 == ap_sig_ioackin_gmem_AWREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_7) & ~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(exitcond_fu_154_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

/// ap_reg_ppiten_pp0_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

/// ap_reg_ppiten_pp0_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

/// ap_reg_ppiten_pp0_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

/// ap_reg_ppiten_pp0_it8 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it8
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(ap_const_logic_0 == ap_sig_ioackin_gmem_AWREADY))) begin
            ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_7) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (exitcond_fu_154_p2 == ap_const_lv1_0))) begin
        i_reg_103 <= i_1_fu_160_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(ap_const_logic_0 == ap_sig_ioackin_gmem_AWREADY))) begin
        i_reg_103 <= ap_const_lv4_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_7) & ~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        ap_reg_ppstg_exitcond_reg_197_pp0_it1 <= exitcond_reg_197;
        exitcond_reg_197 <= exitcond_fu_154_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
        ap_reg_ppstg_exitcond_reg_197_pp0_it2 <= ap_reg_ppstg_exitcond_reg_197_pp0_it1;
        ap_reg_ppstg_exitcond_reg_197_pp0_it3 <= ap_reg_ppstg_exitcond_reg_197_pp0_it2;
        ap_reg_ppstg_exitcond_reg_197_pp0_it4 <= ap_reg_ppstg_exitcond_reg_197_pp0_it3;
        ap_reg_ppstg_exitcond_reg_197_pp0_it5 <= ap_reg_ppstg_exitcond_reg_197_pp0_it4;
        ap_reg_ppstg_exitcond_reg_197_pp0_it6 <= ap_reg_ppstg_exitcond_reg_197_pp0_it5;
        ap_reg_ppstg_exitcond_reg_197_pp0_it7 <= ap_reg_ppstg_exitcond_reg_197_pp0_it6;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_7) & (exitcond_reg_197 == ap_const_lv1_0) & ~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        gmem_addr_1_read_reg_206 <= gmem_RDATA;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it6))) begin
        tmp_2_reg_217 <= grp_fu_171_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        tmp_4_reg_181 <= {{x[ap_const_lv32_1F : ap_const_lv32_2]}};
        tmp_reg_176 <= {{y[ap_const_lv32_1F : ap_const_lv32_2]}};
    end
end

/// ap_done assign process. ///
always @ (gmem_BVALID or ap_sig_cseq_ST_st20_fsm_11)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_11) & ~(gmem_BVALID == ap_const_logic_0))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (gmem_BVALID or ap_sig_cseq_ST_st20_fsm_11)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_11) & ~(gmem_BVALID == ap_const_logic_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_7 assign process. ///
always @ (ap_sig_bdd_246)
begin
    if (ap_sig_bdd_246) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_7 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_7 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_53)
begin
    if (ap_sig_bdd_53) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st20_fsm_11 assign process. ///
always @ (ap_sig_bdd_356)
begin
    if (ap_sig_bdd_356) begin
        ap_sig_cseq_ST_st20_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st20_fsm_11 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_220)
begin
    if (ap_sig_bdd_220) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st7_fsm_6 assign process. ///
always @ (ap_sig_bdd_233)
begin
    if (ap_sig_bdd_233) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

/// ap_sig_ioackin_gmem_ARREADY assign process. ///
always @ (gmem_ARREADY or ap_reg_ioackin_gmem_ARREADY)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_gmem_ARREADY)) begin
        ap_sig_ioackin_gmem_ARREADY = gmem_ARREADY;
    end else begin
        ap_sig_ioackin_gmem_ARREADY = ap_const_logic_1;
    end
end

/// ap_sig_ioackin_gmem_AWREADY assign process. ///
always @ (gmem_AWREADY or ap_reg_ioackin_gmem_AWREADY)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_gmem_AWREADY)) begin
        ap_sig_ioackin_gmem_AWREADY = gmem_AWREADY;
    end else begin
        ap_sig_ioackin_gmem_AWREADY = ap_const_logic_1;
    end
end

/// ap_sig_ioackin_gmem_WREADY assign process. ///
always @ (gmem_WREADY or ap_reg_ioackin_gmem_WREADY)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_gmem_WREADY)) begin
        ap_sig_ioackin_gmem_WREADY = gmem_WREADY;
    end else begin
        ap_sig_ioackin_gmem_WREADY = ap_const_logic_1;
    end
end

/// gmem_ARVALID assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or ap_reg_ioackin_gmem_ARREADY)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_logic_0 == ap_reg_ioackin_gmem_ARREADY))) begin
        gmem_ARVALID = ap_const_logic_1;
    end else begin
        gmem_ARVALID = ap_const_logic_0;
    end
end

/// gmem_AWVALID assign process. ///
always @ (ap_sig_cseq_ST_st7_fsm_6 or ap_reg_ioackin_gmem_AWREADY)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & (ap_const_logic_0 == ap_reg_ioackin_gmem_AWREADY))) begin
        gmem_AWVALID = ap_const_logic_1;
    end else begin
        gmem_AWVALID = ap_const_logic_0;
    end
end

/// gmem_BREADY assign process. ///
always @ (gmem_BVALID or ap_sig_cseq_ST_st20_fsm_11)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_11) & ~(gmem_BVALID == ap_const_logic_0))) begin
        gmem_BREADY = ap_const_logic_1;
    end else begin
        gmem_BREADY = ap_const_logic_0;
    end
end

/// gmem_RREADY assign process. ///
always @ (exitcond_reg_197 or ap_sig_cseq_ST_pp0_stg0_fsm_7 or ap_sig_bdd_254 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_197_pp0_it7 or ap_sig_ioackin_gmem_WREADY or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_7) & (exitcond_reg_197 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        gmem_RREADY = ap_const_logic_1;
    end else begin
        gmem_RREADY = ap_const_logic_0;
    end
end

/// gmem_WVALID assign process. ///
always @ (ap_sig_bdd_254 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_197_pp0_it7 or ap_reg_ppiten_pp0_it8 or ap_reg_ioackin_gmem_WREADY)
begin
    if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & ~(ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_logic_0 == ap_reg_ioackin_gmem_WREADY))) begin
        gmem_WVALID = ap_const_logic_1;
    end else begin
        gmem_WVALID = ap_const_logic_0;
    end
end

/// grp_fu_171_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_7 or ap_sig_bdd_254 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_197_pp0_it7 or ap_sig_ioackin_gmem_WREADY or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_7) & ~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        grp_fu_171_ce = ap_const_logic_1;
    end else begin
        grp_fu_171_ce = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or gmem_BVALID or ap_sig_ioackin_gmem_ARREADY or ap_sig_ioackin_gmem_AWREADY or exitcond_fu_154_p2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_254 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_exitcond_reg_197_pp0_it7 or ap_sig_ioackin_gmem_WREADY or ap_reg_ppiten_pp0_it8)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(ap_const_logic_0 == ap_sig_ioackin_gmem_ARREADY)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : 
        begin
            if (~(ap_const_logic_0 == ap_sig_ioackin_gmem_AWREADY)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_7;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_pp0_stg0_fsm_7 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & ~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it7)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(exitcond_fu_154_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_7;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & ~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it7)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_0 == ap_sig_ioackin_gmem_WREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(exitcond_fu_154_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st17_fsm_8;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_7;
            end
        end
        ap_ST_st17_fsm_8 : 
        begin
            ap_NS_fsm = ap_ST_st18_fsm_9;
        end
        ap_ST_st18_fsm_9 : 
        begin
            ap_NS_fsm = ap_ST_st19_fsm_10;
        end
        ap_ST_st19_fsm_10 : 
        begin
            ap_NS_fsm = ap_ST_st20_fsm_11;
        end
        ap_ST_st20_fsm_11 : 
        begin
            if (~(gmem_BVALID == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st20_fsm_11;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_return = ap_const_lv32_0;

/// ap_rst_n_inv assign process. ///
always @ (ap_rst_n)
begin
    ap_rst_n_inv = ~ap_rst_n;
end

/// ap_sig_bdd_220 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_220 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_233 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_233 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end

/// ap_sig_bdd_246 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_246 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_7]);
end

/// ap_sig_bdd_254 assign process. ///
always @ (gmem_RVALID or exitcond_reg_197)
begin
    ap_sig_bdd_254 = ((gmem_RVALID == ap_const_logic_0) & (exitcond_reg_197 == ap_const_lv1_0));
end

/// ap_sig_bdd_356 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_356 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end

/// ap_sig_bdd_446 assign process. ///
always @ (ap_reg_ppstg_exitcond_reg_197_pp0_it7 or ap_reg_ppiten_pp0_it8)
begin
    ap_sig_bdd_446 = ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_197_pp0_it7) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8));
end

/// ap_sig_bdd_447 assign process. ///
always @ (gmem_WREADY or ap_sig_bdd_254 or ap_reg_ppiten_pp0_it1)
begin
    ap_sig_bdd_447 = ((ap_const_logic_1 == gmem_WREADY) & ~(ap_sig_bdd_254 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)));
end

/// ap_sig_bdd_53 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_53 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end
assign exitcond_fu_154_p2 = (i_reg_103 == ap_const_lv4_A? 1'b1: 1'b0);
assign gmem_ARADDR = tmp_6_fu_134_p1;
assign gmem_ARBURST = ap_const_lv2_0;
assign gmem_ARCACHE = ap_const_lv4_0;
assign gmem_ARID = ap_const_lv1_0;
assign gmem_ARLEN = ap_const_lv32_A;
assign gmem_ARLOCK = ap_const_lv2_0;
assign gmem_ARPROT = ap_const_lv3_0;
assign gmem_ARQOS = ap_const_lv4_0;
assign gmem_ARREGION = ap_const_lv4_0;
assign gmem_ARSIZE = ap_const_lv3_0;
assign gmem_ARUSER = ap_const_lv1_0;
assign gmem_AWADDR = tmp_5_fu_144_p1;
assign gmem_AWBURST = ap_const_lv2_0;
assign gmem_AWCACHE = ap_const_lv4_0;
assign gmem_AWID = ap_const_lv1_0;
assign gmem_AWLEN = ap_const_lv32_A;
assign gmem_AWLOCK = ap_const_lv2_0;
assign gmem_AWPROT = ap_const_lv3_0;
assign gmem_AWQOS = ap_const_lv4_0;
assign gmem_AWREGION = ap_const_lv4_0;
assign gmem_AWSIZE = ap_const_lv3_0;
assign gmem_AWUSER = ap_const_lv1_0;
assign gmem_WDATA = tmp_2_reg_217;
assign gmem_WID = ap_const_lv1_0;
assign gmem_WLAST = ap_const_logic_0;
assign gmem_WSTRB = ap_const_lv4_F;
assign gmem_WUSER = ap_const_lv1_0;
assign grp_fu_171_p0 = gmem_addr_1_read_reg_206;
assign grp_fu_171_p1 = ($signed(gmem_addr_1_read_reg_206) + $signed(ap_const_lv32_1));
assign i_1_fu_160_p2 = (i_reg_103 + ap_const_lv4_1);
assign multi_axim_AXILiteS_s_axi_U_ap_dummy_ce = ap_const_logic_1;
assign multi_axim_gmem_m_axi_U_ap_dummy_ce = ap_const_logic_1;
assign tmp_5_fu_144_p1 = tmp_reg_176;
assign tmp_6_fu_134_p1 = tmp_4_reg_181;


endmodule //multi_axim

