// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XMULTI_AXIM_H
#define XMULTI_AXIM_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmulti_axim_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XMulti_axim_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XMulti_axim;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMulti_axim_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMulti_axim_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMulti_axim_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMulti_axim_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMulti_axim_Initialize(XMulti_axim *InstancePtr, u16 DeviceId);
XMulti_axim_Config* XMulti_axim_LookupConfig(u16 DeviceId);
int XMulti_axim_CfgInitialize(XMulti_axim *InstancePtr, XMulti_axim_Config *ConfigPtr);
#else
int XMulti_axim_Initialize(XMulti_axim *InstancePtr, const char* InstanceName);
int XMulti_axim_Release(XMulti_axim *InstancePtr);
#endif

void XMulti_axim_Start(XMulti_axim *InstancePtr);
u32 XMulti_axim_IsDone(XMulti_axim *InstancePtr);
u32 XMulti_axim_IsIdle(XMulti_axim *InstancePtr);
u32 XMulti_axim_IsReady(XMulti_axim *InstancePtr);
void XMulti_axim_EnableAutoRestart(XMulti_axim *InstancePtr);
void XMulti_axim_DisableAutoRestart(XMulti_axim *InstancePtr);
u32 XMulti_axim_Get_return(XMulti_axim *InstancePtr);

void XMulti_axim_Set_x(XMulti_axim *InstancePtr, u32 Data);
u32 XMulti_axim_Get_x(XMulti_axim *InstancePtr);
void XMulti_axim_Set_y(XMulti_axim *InstancePtr, u32 Data);
u32 XMulti_axim_Get_y(XMulti_axim *InstancePtr);

void XMulti_axim_InterruptGlobalEnable(XMulti_axim *InstancePtr);
void XMulti_axim_InterruptGlobalDisable(XMulti_axim *InstancePtr);
void XMulti_axim_InterruptEnable(XMulti_axim *InstancePtr, u32 Mask);
void XMulti_axim_InterruptDisable(XMulti_axim *InstancePtr, u32 Mask);
void XMulti_axim_InterruptClear(XMulti_axim *InstancePtr, u32 Mask);
u32 XMulti_axim_InterruptGetEnabled(XMulti_axim *InstancePtr);
u32 XMulti_axim_InterruptGetStatus(XMulti_axim *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
