// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmulti_axim.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMulti_axim_CfgInitialize(XMulti_axim *InstancePtr, XMulti_axim_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMulti_axim_Start(XMulti_axim *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMulti_axim_ReadReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_AP_CTRL) & 0x80;
    XMulti_axim_WriteReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMulti_axim_IsDone(XMulti_axim *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMulti_axim_ReadReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMulti_axim_IsIdle(XMulti_axim *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMulti_axim_ReadReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMulti_axim_IsReady(XMulti_axim *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMulti_axim_ReadReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMulti_axim_EnableAutoRestart(XMulti_axim *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMulti_axim_WriteReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XMulti_axim_DisableAutoRestart(XMulti_axim *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMulti_axim_WriteReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XMulti_axim_Get_return(XMulti_axim *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMulti_axim_ReadReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_AP_RETURN);
    return Data;
}
void XMulti_axim_Set_x(XMulti_axim *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMulti_axim_WriteReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_X_DATA, Data);
}

u32 XMulti_axim_Get_x(XMulti_axim *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMulti_axim_ReadReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_X_DATA);
    return Data;
}

void XMulti_axim_Set_y(XMulti_axim *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMulti_axim_WriteReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_Y_DATA, Data);
}

u32 XMulti_axim_Get_y(XMulti_axim *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMulti_axim_ReadReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_Y_DATA);
    return Data;
}

void XMulti_axim_InterruptGlobalEnable(XMulti_axim *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMulti_axim_WriteReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_GIE, 1);
}

void XMulti_axim_InterruptGlobalDisable(XMulti_axim *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMulti_axim_WriteReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_GIE, 0);
}

void XMulti_axim_InterruptEnable(XMulti_axim *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMulti_axim_ReadReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_IER);
    XMulti_axim_WriteReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_IER, Register | Mask);
}

void XMulti_axim_InterruptDisable(XMulti_axim *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMulti_axim_ReadReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_IER);
    XMulti_axim_WriteReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_IER, Register & (~Mask));
}

void XMulti_axim_InterruptClear(XMulti_axim *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMulti_axim_WriteReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_ISR, Mask);
}

u32 XMulti_axim_InterruptGetEnabled(XMulti_axim *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMulti_axim_ReadReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_IER);
}

u32 XMulti_axim_InterruptGetStatus(XMulti_axim *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMulti_axim_ReadReg(InstancePtr->Axilites_BaseAddress, XMULTI_AXIM_AXILITES_ADDR_ISR);
}

